# Effectivness of lockdowns

**Goal**: check to see if there is a correlation between lockdowns and cumulative death count per million.

# Data

## Lockdown severity

* [CORONAVIRUS GOVERNMENT RESPONSE TRACKER](https://www.bsg.ox.ac.uk/research/research-projects/coronavirus-government-response-tracker#data)
* [Wikipedia](https://en.wikipedia.org/wiki/National_responses_to_the_COVID-19_pandemic#Lockdowns)

### CORONAVIRUS GOVERNMENT RESPONSE TRACKER

CX_Flag -- indicates scope:
* 0 -- targeted
* 1 -- general

## Deaths

* [COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19)
* [England & Wales](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/deathsregisteredweeklyinenglandandwalesprovisional/weekending8january2021)

# Ideas

In order to measure the effectiveness of lockdowns we could look at:
* Cum Death distribution between number of days (C6 >=2, C7 >= 1 and C6_Flag = C7_Flag = 1) vs (C6 < 2, C7 = 0 and C6_Flag=C7_Flag=1). Box plot. Kullback-Leibler divergence.
* Correlation between StringencyIndex and Cum Death count
* Correlation between pct of days spent in a lockdown vs total deaths per million.

# Open questions
* What countries have RegionName != [nan]? And how should we deal with matching deaths with StringencyIndex of countries that have stats by region?
* How does GDP impact death count? Maybe some countries have health systems that can afford having all their severe cases in ICUs?
* How age of population impacts the stats? What if countries that have no lockdown and small death counts are simply just younger?

In [1]:
import pandas as pd

In [16]:
lockdowns = pd.read_csv('OxCGRT_latest.csv')

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
lockdowns.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# which countries have regions
lockdowns[lockdowns['RegionName'].notnull()].CountryName.unique()

array(['Brazil', 'Canada', 'United Kingdom', 'United States'],
      dtype=object)

In [19]:
covid = pd.read_csv('owid-covid-data.csv')
covid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498

Can join the `owid-covid-data.csv` with `OxCGRT_latest.csv` data on `iso_code` and `CountryCode` respectively but `owid-covid-data.csv` does not have data split by regions, so for countries:
* Brazil
* Canada
* United Kingdom
* United States

would need additional data or just need to find a better dataset. So far this will be enough since I can only start with Europe (excluding UK) and also check Asia (excluding China, Iran and maybe some others with dodgy stats), Africa.

In [20]:
lockdowns[lockdowns.CountryName == 'United Kingdom'].RegionName.unique()

array([nan, 'England', 'Northern Ireland', 'Scotland', 'Wales'],
      dtype=object)

In [22]:
lockdowns[lockdowns.StringencyIndex == 100].CountryName.unique()

array(['Argentina', 'Cuba', 'Dominican Republic', 'Georgia', 'Honduras',
       'India', 'Jordan', 'Kuwait', 'Libya', 'Sri Lanka', 'Oman',
       'Philippines', 'El Salvador', 'Serbia', 'Suriname'], dtype=object)